export interface Template {
  slug: string;
  name: string;
  category: string;
  tagline: string;
  description: string;
  demoUrl: string | null;
  previewImage: string;
  gallery: string[];
  features: string[];
  targetAudience: string;
  tech: string[];
  capabilities: string[];
  sortOrder?: number;
  hidden?: boolean;
}

const STD_FEATURES = [
  "Búsqueda inteligente con filtros avanzados",
  "Galería inmersiva de propiedades",
  "Embudo de calificación de 6 pasos",
  "Mapa interactivo con Mapbox",
  "Ficha de detalle enriquecida",
  "SEO optimizado por propiedad",
];
const STD_TECH = ["Mapbox", "Embudo 6 pasos"];
const STD_CAPS = ["HeroSearchV1", "PropertyGridV2", "PropertyDetailsV3", "LeadCaptureFormV2"];

// ─── Protegidos (sitios con asesor real) ─────────────────────────────────────

export const TEMPLATES: Template[] = [
  {
    slug: "raquel-melendez",
    name: "Raquel Meléndez",
    category: "luxury-real-estate",
    tagline: "Lujo y exclusividad con presencia digital de alto impacto",
    description:
      "Diseño sofisticado para brokers de lujo. Búsqueda inteligente, valuación con IA, galería inmersiva y embudo de calificación de 6 pasos.",
    demoUrl: "https://raquelmelendrez.homepty.com",
    previewImage: "/demos/raquel-melendez/cover.webp",
    gallery: [
      "/demos/raquel-melendez/gallery-01.webp",
      "/demos/raquel-melendez/gallery-02.webp",
      "/demos/raquel-melendez/gallery-03.webp",
    ],
    features: [...STD_FEATURES, "Valuación de propiedades con IA", "Blog vinculado a propiedades", "Citas virtuales integradas"],
    targetAudience: "Brokers de lujo",
    tech: ["Mapbox", "Valuación IA", "Embudo 6 pasos", "Blog"],
    capabilities: [...STD_CAPS, "ValuationChartV1"],
    sortOrder: 1,
  },
  {
    slug: "frank-co",
    name: "Frank Co Asesores",
    category: "agency",
    tagline: "Sitio moderno para equipos de asesores",
    description: "Diseño profesional para equipos con portafolio diversificado. Búsqueda avanzada y captura de leads integrada.",
    demoUrl: "https://frankcoasesores.homepty.com",
    previewImage: "/demos/frank-co/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Equipos de asesores",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 2,
  },
  {
    slug: "all-home",
    name: "All Home Bienes Raíces",
    category: "agency",
    tagline: "Todo bajo un mismo techo digital",
    description: "Plataforma completa con dominio propio, grid de propiedades y embudo de conversión de alto rendimiento.",
    demoUrl: "https://allhome.homepty.com",
    previewImage: "/demos/all-home/cover.webp",
    gallery: [],
    features: [...STD_FEATURES, "Dominio personalizado"],
    targetAudience: "Agencias con dominio propio",
    tech: [...STD_TECH, "Dominio personalizado"],
    capabilities: STD_CAPS,
    sortOrder: 3,
  },
  {
    slug: "ijb-asesoria",
    name: "IJB Asesoría",
    category: "broker",
    tagline: "Sitio personal de alto impacto para asesores independientes",
    description: "Diseño personal y elegante con portafolio propio y contacto directo.",
    demoUrl: "https://betsabeearias.homepty.com",
    previewImage: "/demos/ijb-asesoria/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Asesores independientes",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 4,
  },
  {
    slug: "riasarana",
    name: "RIASARANA Bienes Raíces",
    category: "agency",
    tagline: "Presencia profesional para agencias inmobiliarias",
    description: "Sitio completo con portafolio amplio, filtros y embudo de conversión.",
    demoUrl: "https://sergio.homepty.com",
    previewImage: "/demos/riasarana/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Agencias inmobiliarias",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 5,
  },
  {
    slug: "agencia-template-cbf",
    name: "Agencia Template",
    category: "agency",
    tagline: "Plantilla base con todas las funcionalidades CBF",
    description: "La plantilla fundacional del ecosistema Homepty CBF con todas las funcionalidades activas.",
    demoUrl: "https://agencia-template-cbf.vercel.app",
    previewImage: "/demos/agencia-template-cbf/cover.webp",
    gallery: [],
    features: [...STD_FEATURES, "Valuación IA", "Blog", "Citas virtuales"],
    targetAudience: "Agencias y brokers",
    tech: [...STD_TECH, "Valuación IA", "Blog"],
    capabilities: [...STD_CAPS, "ValuationChartV1"],
    sortOrder: 6,
  },
  {
    slug: "premium-property-hub",
    name: "Premium Property Hub",
    category: "luxury-real-estate",
    tagline: "Propiedades premium con presencia digital exclusiva",
    description: "Plataforma de propiedades premium con diseño de alto impacto.",
    demoUrl: null,
    previewImage: "/demos/premium-property-hub/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Brokers de lujo",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 7,
  },

  // ─── Plantillas genéricas PW (agencia-pw0001 … agencia-pw0038) ───────────

  {
    slug: "agencia-pw0001",
    name: "Plantilla PW-0001",
    category: "broker",
    tagline: "Diseño editorial en dos tiempos — crema y contraste oscuro",
    description: "Distribución split 7/5 en crema con sección invertida oscura. Grid uniforme de propiedades y perfil de asesor.",
    demoUrl: "https://agencia-pw0001.vercel.app",
    previewImage: "/demos/agencia-pw0001/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Asesores independientes",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 10,
  },
  {
    slug: "agencia-pw0002",
    name: "Plantilla PW-0002",
    category: "broker",
    tagline: "Bento grid dinámico con énfasis visual",
    description: "Layout moderno tipo Bento Grid P4 que organiza propiedades y secciones en bloques asimétricos de alto impacto.",
    demoUrl: "https://agencia-pw0002.vercel.app",
    previewImage: "/demos/agencia-pw0002/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Asesores independientes",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 11,
  },
  {
    slug: "agencia-pw0003",
    name: "Plantilla PW-0003",
    category: "broker",
    tagline: "Presencia digital limpia para asesor independiente",
    description: "Diseño minimalista enfocado en la propuesta de valor del asesor con portafolio de propiedades y CTA directos.",
    demoUrl: "https://agencia-pw0003.vercel.app",
    previewImage: "/demos/agencia-pw0003/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Asesores independientes",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 12,
  },
  {
    slug: "agencia-pw0004",
    name: "Plantilla PW-0004",
    category: "broker",
    tagline: "Asesoría estratégica con sitio de alto rendimiento",
    description: "Plataforma personal de asesor con portafolio curado y embudo de calificación inteligente.",
    demoUrl: "https://agencia-pw0004.vercel.app",
    previewImage: "/demos/agencia-pw0004/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Asesores independientes",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 13,
  },
  {
    slug: "agencia-pw0005",
    name: "Plantilla PW-0005",
    category: "broker",
    tagline: "Sitio personal profesional con identidad fuerte",
    description: "Diseño orientado al asesor independiente con secciones de servicios, propiedades y contacto directo.",
    demoUrl: "https://agencia-pw0005.vercel.app",
    previewImage: "/demos/agencia-pw0005/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Asesores independientes",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 14,
  },
  {
    slug: "agencia-pw0006",
    name: "Plantilla PW-0006",
    category: "broker",
    tagline: "Experiencia digital fluida para asesora independiente",
    description: "Sitio personal con galería de propiedades, bio de asesor y formulario de contacto integrado.",
    demoUrl: "https://agencia-pw0006.vercel.app",
    previewImage: "/demos/agencia-pw0006/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Asesoras independientes",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 15,
  },
  {
    slug: "agencia-pw0007",
    name: "Plantilla PW-0007",
    category: "agency",
    tagline: "La mejor elección para tu patrimonio inmobiliario",
    description: "Agencia inmobiliaria con enfoque en guiar al cliente hacia la mejor decisión. Portafolio completo y embudo calificado.",
    demoUrl: "https://agencia-pw0007.vercel.app",
    previewImage: "/demos/agencia-pw0007/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Agencias inmobiliarias",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 16,
  },
  {
    slug: "agencia-pw0008",
    name: "Plantilla PW-0008",
    category: "broker",
    tagline: "Propiedades que generan valor — asesor especializado",
    description: "Sitio profesional con portafolio especializado, mapa interactivo y proceso de calificación de leads.",
    demoUrl: "https://agencia-pw0008.vercel.app",
    previewImage: "/demos/agencia-pw0008/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Asesores independientes",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 17,
  },
  {
    slug: "agencia-pw0009",
    name: "Plantilla PW-0009",
    category: "broker",
    tagline: "Propiedades seleccionadas con criterio experto",
    description: "Diseño elegante para asesor con portafolio curado, sección de servicios y embudo inteligente.",
    demoUrl: "https://agencia-pw0009.vercel.app",
    previewImage: "/demos/agencia-pw0009/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Asesores independientes",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 18,
  },
  {
    slug: "agencia-pw0010",
    name: "Plantilla PW-0010",
    category: "luxury-real-estate",
    tagline: "Editorial asimétrico navy con Bento Grid de lujo",
    description: "Distribución Asymmetric Editorial Split 60/40 en navy. Bento Grid P4 y sección de amenidades de estilo de vida.",
    demoUrl: "https://agencia-pw0010.vercel.app",
    previewImage: "/demos/agencia-pw0010/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Brokers de lujo",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 19,
  },
  {
    slug: "agencia-pw0011",
    name: "Plantilla PW-0011",
    category: "luxury-real-estate",
    tagline: "Hero vertical + grid oro y cristal líquido",
    description: "Hero con Grid Vertical P7, strip navy 3-columnas, transición diagonal y grid con acento dorado & liquid-glass.",
    demoUrl: "https://agencia-pw0011.vercel.app",
    previewImage: "/demos/agencia-pw0011/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Brokers de lujo",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 20,
  },
  {
    slug: "agencia-pw0012",
    name: "Plantilla PW-0012",
    category: "luxury-real-estate",
    tagline: "Noir editorial — magazine, dark glass y masonry oscuro",
    description: "P1 Variante Noir full-bleed oscuro. Magazine Split 60/40, 3-Column Dark Strip y Dark Glass Masonry Grid exclusivo.",
    demoUrl: "https://agencia-pw0012.vercel.app",
    previewImage: "/demos/agencia-pw0012/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Brokers de lujo",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 21,
  },
  {
    slug: "agencia-pw0013",
    name: "Plantilla PW-0013",
    category: "agency",
    tagline: "Cinematográfico asimétrico con bento grid y acero azul",
    description: "Hero Cinematic Asymmetric Editorial, 4-Column Bento Grid P4, Diagonal Expansion Transition y Liquid-Glass Steel-Blue Grid.",
    demoUrl: "https://agencia-pw0013.vercel.app",
    previewImage: "/demos/agencia-pw0013/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Agencias inmobiliarias",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 22,
  },
  {
    slug: "agencia-pw0014",
    name: "Plantilla PW-0014",
    category: "luxury-real-estate",
    tagline: "Cinematográfico borgoña y oro — full-bleed de lujo",
    description: "P1 Full-Bleed Cinematic en Burgundy. 4-Stat Strip dorado, servicios 3-columnas y Asymmetric Masonry liquid-glass.",
    demoUrl: "https://agencia-pw0014.vercel.app",
    previewImage: "/demos/agencia-pw0014/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Brokers de lujo",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 23,
  },
  {
    slug: "agencia-pw0015",
    name: "Plantilla PW-0015",
    category: "luxury-real-estate",
    tagline: "Bento editorial con grid-Z asimétrico y acento dorado",
    description: "Bento Grid Editorial con texto flotante, 3-Column Dark Strip dorado, Asymmetric Staggered Z-Grid y Immersive Strip.",
    demoUrl: "https://agencia-pw0015.vercel.app",
    previewImage: "/demos/agencia-pw0015/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Brokers de lujo",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 24,
  },
  {
    slug: "agencia-pw0016",
    name: "Plantilla PW-0016",
    category: "developer",
    tagline: "Proptech gallery — minimalista y glassmorphic",
    description: "P11 Staggered Proptech Gallery, 3-Column Light Cards, Minimalist Proptech Grid y Floating Glassmorphic Bio.",
    demoUrl: "https://agencia-pw0016.vercel.app",
    previewImage: "/demos/agencia-pw0016/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Desarrolladoras e inversores",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 25,
  },
  {
    slug: "agencia-pw0017",
    name: "Plantilla PW-0017",
    category: "luxury-real-estate",
    tagline: "Mármol Carrara, índigo glassmorphic y bento collage",
    description: "Mag-Cover Editorial glassmorphic índigo, Marble Editorial Carrara, Diagonal Mirror Hover y Asymmetric Bento Collage dorado.",
    demoUrl: "https://agencia-pw0017.vercel.app",
    previewImage: "/demos/agencia-pw0017/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Brokers de lujo",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 26,
  },
  {
    slug: "agencia-pw0018",
    name: "Plantilla PW-0018",
    category: "agency",
    tagline: "Signal board noir con timeline amarillo y bookmark grid",
    description: "P16 Signal Board Noir con marca masiva condensed, Timeline Vertical amarillo, Yellow Bookmark Grid y Portrait Circle Board.",
    demoUrl: "https://agencia-pw0018.vercel.app",
    previewImage: "/demos/agencia-pw0018/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Agencias y despachos inmobiliarios",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 27,
  },
  {
    slug: "agencia-pw0019",
    name: "Plantilla PW-0019",
    category: "luxury-real-estate",
    tagline: "Luxury plum cinemático con stat strip dorado",
    description: "P16 Luxury Plum Cinematic, Editorial Portfolio 60/40, Premium Satin Gold Stat Strip y Floating Glass Bento Collage.",
    demoUrl: "https://agencia-pw0019.vercel.app",
    previewImage: "/demos/agencia-pw0019/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Brokers de lujo",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 28,
  },
  {
    slug: "agencia-pw0020",
    name: "Plantilla PW-0020",
    category: "broker",
    tagline: "Claymorphic swipe interactivo con pop-art",
    description: "P21 Claymorphic Swipe Cinematic, Note Grid corcho, Bento Glassmorphic con emoji badges y Pop-Art Shell Portrait.",
    demoUrl: "https://agencia-pw0020.vercel.app",
    previewImage: "/demos/agencia-pw0020/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Asesores con marca personal joven",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 29,
  },
  {
    slug: "agencia-pw0021",
    name: "Plantilla PW-0021",
    category: "developer",
    tagline: "Ejecutivo minimalista horizon con slider VCRI interactivo",
    description: "P26 Executive Minimalist Horizon, VCRI Interactive Slider/Grid, Bento Objectives Board y Executive Minimalist Grid.",
    demoUrl: "https://agencia-pw0021.vercel.app",
    previewImage: "/demos/agencia-pw0021/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Desarrolladoras e inversores",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 30,
  },
  {
    slug: "agencia-pw0022",
    name: "Plantilla PW-0022",
    category: "broker",
    tagline: "Canvas horizon editorial — cristal minimalista y bento suave",
    description: "P31 Canvas Horizon Editorial, Canvas Contrast, Minimalist Glass Leaflets y Smooth Canvas Bento Grid.",
    demoUrl: "https://agencia-pw0022.vercel.app",
    previewImage: "/demos/agencia-pw0022/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Asesores independientes",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 31,
  },
  {
    slug: "agencia-pw0023",
    name: "Plantilla PW-0023",
    category: "agency",
    tagline: "SVG animado navy — servicios glass y propiedades canvas",
    description: "P36a Animated SVG House Canvas navy, Servicios 3-Col Glass Grid dorado, Properties Canvas Grid y Contacto Canvas Strip.",
    demoUrl: "https://agencia-pw0023.vercel.app",
    previewImage: "/demos/agencia-pw0023/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Agencias inmobiliarias",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 32,
  },
  {
    slug: "agencia-pw0024",
    name: "Plantilla PW-0024",
    category: "agency",
    tagline: "Linen drift inmersivo — tipográfico puro y ghost glass",
    description: "P37 Immersive Linen Drift con marca masiva, editorial 2-col, servicios tipográfico puro 4-col y Ghost Glass Grid.",
    demoUrl: "https://agencia-pw0024.vercel.app",
    previewImage: "/demos/agencia-pw0024/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Agencias inmobiliarias",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 33,
  },
  {
    slug: "agencia-pw0025",
    name: "Plantilla PW-0025",
    category: "agency",
    tagline: "Canvas beige inmersivo — marca ghost y glass bento",
    description: "P38a Immersive Beige Canvas Hero con ghost lettermark, Editorial 2-col, Staggered Services List y Ghost Glass Grid.",
    demoUrl: "https://agencia-pw0025.vercel.app",
    previewImage: "/demos/agencia-pw0025/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Grupos inmobiliarios",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 34,
  },
  {
    slug: "agencia-pw0026",
    name: "Plantilla PW-0026",
    category: "agency",
    tagline: "Canvas orgánico editorial — bento papel y olive grid",
    description: "P39 Organic Editorial Text Canvas, Roots Philosophy con outline, Three-column Olive Services Grid y Bento Paper Collage.",
    demoUrl: "https://agencia-pw0026.vercel.app",
    previewImage: "/demos/agencia-pw0026/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Agencias con identidad orgánica",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 35,
  },
  {
    slug: "agencia-pw0027",
    name: "Plantilla PW-0027",
    category: "broker",
    tagline: "Script canvas inmersivo — manifesto tipográfico Pinyon",
    description: "P43a Immersive Script Canvas Hero, Index Manifesto Typographic 3-col, Rounded Editorial Grid y Oversized Bio display.",
    demoUrl: "https://agencia-pw0027.vercel.app",
    previewImage: "/demos/agencia-pw0027/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Asesores independientes",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 36,
  },
  {
    slug: "agencia-pw0028",
    name: "Plantilla PW-0028",
    category: "broker",
    tagline: "Monocromático inmersivo — timeline infográfico de 4 pasos",
    description: "P44 Immersive Monochrome Search, P45 Infographic Step Timeline hover, P46 Monochromatic Rounded Collage y Portrait Reveal.",
    demoUrl: "https://agencia-pw0028.vercel.app",
    previewImage: "/demos/agencia-pw0028/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Asesores independientes",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 37,
  },
  {
    slug: "agencia-pw0029",
    name: "Plantilla PW-0029",
    category: "luxury-real-estate",
    tagline: "Velvet oscuro inmersivo — ejecutivo platino y liquid grid",
    description: "P48 Dark Velvet Canvas, P49 Manifesto Executive Minimalist, P51 Liquid Dark Grid y P52 Platinum Executive Bio.",
    demoUrl: "https://agencia-pw0029.vercel.app",
    previewImage: "/demos/agencia-pw0029/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Brokers de lujo",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 38,
  },
  {
    slug: "agencia-pw0030",
    name: "Plantilla PW-0030",
    category: "agency",
    tagline: "Canvas frío — editorial fluido y columnas hairline platinum",
    description: "P53a Frosted Elevation Canvas con ghost lettermark, Fluid Identity Editorial, Hairline Columns Services y Platinum Glass Grid.",
    demoUrl: "https://agencia-pw0030.vercel.app",
    previewImage: "/demos/agencia-pw0030/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Agencias inmobiliarias",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 39,
  },
  {
    slug: "agencia-pw0031",
    name: "Plantilla PW-0031",
    category: "agency",
    tagline: "Industrial steel horizon — connected corridors y terminal",
    description: "P54a Industrial Steel Horizon con ghost lettermark 50vw, Connected Corridors de valor, Immersive Grid Industrial y Terminal ejecutivo.",
    demoUrl: "https://agencia-pw0031.vercel.app",
    previewImage: "/demos/agencia-pw0031/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Agencias regionales e industriales",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 40,
  },
  {
    slug: "agencia-pw0032",
    name: "Plantilla PW-0032",
    category: "agency",
    tagline: "Agencia inmobiliaria con portafolio diversificado",
    description: "Plataforma digital para agencia con catálogo completo, búsqueda avanzada y captura de leads calificados.",
    demoUrl: "https://agencia-pw0032.vercel.app",
    previewImage: "/demos/agencia-pw0032/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Agencias inmobiliarias",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 41,
  },
  {
    slug: "agencia-pw0033",
    name: "Plantilla PW-0033",
    category: "broker",
    tagline: "Asesoría inmobiliaria con trayectoria y resultados",
    description: "Sitio personal de asesor con portafolio especializado y proceso de calificación optimizado.",
    demoUrl: "https://agencia-pw0033.vercel.app",
    previewImage: "/demos/agencia-pw0033/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Asesores independientes",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 42,
  },
  {
    slug: "agencia-pw0034",
    name: "Plantilla PW-0034",
    category: "agency",
    tagline: "Agencia inmobiliaria con identidad visual fuerte",
    description: "Plataforma con identidad de marca definida, catálogo de propiedades y embudo de conversión profesional.",
    demoUrl: "https://agencia-pw0034.vercel.app",
    previewImage: "/demos/agencia-pw0034/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Agencias inmobiliarias",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 43,
  },
  {
    slug: "agencia-pw0035",
    name: "Plantilla PW-0035",
    category: "agency",
    tagline: "Portafolio de propiedades con experiencia digital fluida",
    description: "Diseño enfocado en conversión con búsqueda inteligente, grid de propiedades y contacto directo.",
    demoUrl: "https://agencia-pw0035.vercel.app",
    previewImage: "/demos/agencia-pw0035/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Agencias inmobiliarias",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 44,
  },
  {
    slug: "agencia-pw0036",
    name: "Plantilla PW-0036",
    category: "broker",
    tagline: "Experiencia digital de alto impacto para asesor",
    description: "Sitio personal con diseño moderno, portafolio de propiedades y sistema de captación inteligente.",
    demoUrl: "https://agencia-pw0036.vercel.app",
    previewImage: "/demos/agencia-pw0036/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Asesores independientes",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 45,
  },
  {
    slug: "agencia-pw0037",
    name: "Plantilla PW-0037",
    category: "agency",
    tagline: "Grupo inmobiliario con portafolio corporativo",
    description: "Sitio corporativo para grupos con portafolio amplio, filtros avanzados y embudo de calificación.",
    demoUrl: "https://agencia-pw0037.vercel.app",
    previewImage: "/demos/agencia-pw0037/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Grupos inmobiliarios",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 46,
  },
  {
    slug: "agencia-pw0038",
    name: "Plantilla PW-0038",
    category: "broker",
    tagline: "Sitio personal elegante con enfoque en conversión",
    description: "Diseño personal con portafolio curado, sección de servicios y proceso de calificación de alto rendimiento.",
    demoUrl: "https://agencia-pw0038.vercel.app",
    previewImage: "/demos/agencia-pw0038/cover.webp",
    gallery: [],
    features: STD_FEATURES,
    targetAudience: "Asesores independientes",
    tech: STD_TECH,
    capabilities: STD_CAPS,
    sortOrder: 47,
  },
];

export function getTemplates(): Template[] {
  return TEMPLATES.filter((t) => !t.hidden).sort(
    (a, b) => (a.sortOrder ?? 99) - (b.sortOrder ?? 99)
  );
}

export function getTemplateBySlug(slug: string): Template | undefined {
  return TEMPLATES.find((t) => t.slug === slug);
}
